app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('supriya/',supriya,name='supriya'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('contact/',contact,name='contact'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('task/',task,name='task'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def supriya(request):
    return render(request,'supriya.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request,'contact.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def task(request):
    return render(request,'task.html')

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
</head>
<body>
    <center>
        <h1>She is a beatiful girl and very ennocent</h1>
        <h2>Ph:9876543210</h2>
        <h2>insta:supriya_priya</h2>
        <a href="{% url 'task' %}"><h1> First complete the task</h1></a>
    </center>
</body>
</html>

templates/supriya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>supriya</title>
</head>
<body>
    <center>
        <h1>supriya is a single</h1>
        <h1>If anyone intrested</h1>
        <a href="{% url 'app2:contact' %}"><h1>Click Here</h1></a>
    </center>
</body>
</html>

templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>task</title>
</head>
<body>
    <center>
        <h1>First remove your Drinking habit </h1>
    </center>
    
</body>
</html>